# Generated by Django 3.2.12 on 2022-05-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teslahapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.CreateModel(
            name='image_publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='image/')),
                ('publication', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teslahapp.publication')),
            ],
        ),
    ]
