# Generated by Django 3.2.12 on 2022-05-06 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('gender', models.CharField(choices=[('male', 'Homme'), ('Female', 'Femme')], default='male', max_length=10)),
                ('date_naissance', models.DateField(null=True)),
                ('Specialite', models.CharField(choices=[('Electrique', 'Electrique'), ('Mécanique_Auto', 'Mecanique'), ('Climatisation', 'Climatisation'), ('Plombérie', 'Plombérie'), ('Menuiserie', 'Menuiserie')], default='------', max_length=20, null=True)),
                ('annee_experience', models.PositiveIntegerField(null=True)),
                ('cv', models.FileField(null=True, upload_to='CV/')),
                ('NNI', models.CharField(max_length=10, null=True)),
                ('Date_inscription', models.DateTimeField(auto_now_add=True, null=True)),
                ('num_tel', models.CharField(max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
