# Generated by Django 3.2.12 on 2022-05-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='statut',
            field=models.CharField(default='P', max_length=40),
        ),
    ]
